source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.7'

gem 'rails',    '~> 6.0.2', '>= 6.0.2.1'
gem 'puma',     '~> 4.1'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'bcrypt',   '~> 3.1.7'

gem 'rack-cors'
gem 'graphql'
gem 'knock'
gem 'dotenv-rails'

group :development, :test do
  gem 'sqlite3', '~> 1.4'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :production do
  gem 'pg', '~> 0.18.4'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
